# Generated by Django 6.0.7 on 2026-08-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', help_text='Preferred language for auto-translation', max_length=10),
        ),
    ]
