# Generated by Django 6.0.7 on 2026-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_conversation', 'New Conversation'), ('new_message', 'New Message'), ('assignment', 'Assignment'), ('mention', 'Mention'), ('escalation', 'Escalation')], max_length=30),
        ),
    ]
