# Generated by Django 6.0.7 on 2026-07-31 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_read_at'),
        ('teams', '0002_create_missing_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='teams.team'),
        ),
    ]
