# Generated by Django 6.0.7 on 2026-07-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_add_team_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
