# Generated by Django 6.0.7 on 2026-08-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_add_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ticket_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
