# Generated by Django 6.0.7 on 2026-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_assign_ticket_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='detected_language',
            field=models.CharField(blank=True, default='', help_text='Detected language code', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='original_body',
            field=models.TextField(blank=True, default='', help_text='Original text before translation'),
        ),
    ]
