# Generated by Django 6.0.7 on 2026-07-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('company_name', models.CharField(default='Connect', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_conversation_alert', models.BooleanField(default=True)),
                ('message_from_visitor', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('mention_alert', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('border_radius', models.IntegerField(default=16)),
                ('auto_greet', models.BooleanField(default=True)),
                ('auto_greet_delay', models.IntegerField(default=3)),
                ('collect_email', models.BooleanField(default=True)),
                ('show_branding', models.BooleanField(default=True)),
                ('help_center_enabled', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='accounts.organization')),
            ],
        ),
    ]
