# Generated by Django 6.0.7 on 2026-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='faqs_display_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='show_faqs_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
