# Generated by Django 6.0.7 on 2026-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_widgetconfig_faqs_display_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/logos/'),
        ),
    ]
