# Generated by Django 6.0.7 on 2026-08-01 14:53

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_verificationcode'),
        ('conversations', '0006_assign_ticket_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(choices=[('openai/gpt-4o-mini', 'GPT-4o Mini'), ('openai/gpt-4o', 'GPT-4o'), ('anthropic/claude-3.5-sonnet', 'Claude 3.5 Sonnet'), ('google/gemini-2.0-flash-001', 'Gemini 2.0 Flash')], default='openai/gpt-4o-mini', max_length=100)),
                ('embedding_model', models.CharField(choices=[('openai/text-embedding-3-small', 'Text Embedding 3 Small'), ('openai/text-embedding-3-large', 'Text Embedding 3 Large')], default='openai/text-embedding-3-small', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=512)),
                ('system_prompt', models.TextField(blank=True, default="You are a helpful customer support assistant. Answer questions accurately and concisely based on the provided context. If you're unsure or the question is about something not in the context, say you'll connect them with a human agent.")),
                ('escalate_on_angry', models.BooleanField(default=True)),
                ('escalate_on_low_confidence', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.5, help_text='Minimum confidence to auto-reply (0-1)')),
                ('max_ai_turns', models.IntegerField(default=5, help_text='Max consecutive AI replies before escalating')),
                ('provider_base_url', models.URLField(blank=True, default='https://openrouter.ai/api/v1', help_text='OpenRouter API base URL (or OmniRoute URL)')),
                ('provider_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIReplyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('sources_used', models.JSONField(blank=True, default=list, help_text='List of source IDs used for context')),
                ('response_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('kb_article', 'Knowledge Base Article'), ('kb_faq', 'Knowledge Base FAQ'), ('website', 'Website Scrape'), ('document', 'Uploaded Document'), ('manual', 'Manual Entry')], max_length=20)),
                ('external_id', models.CharField(blank=True, default='', help_text='ID of linked KB article/FAQ', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sources', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='accounts.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_service.knowledgesource')),
            ],
            options={
                'ordering': ['source', 'chunk_index'],
            },
        ),
    ]
