# Generated by Django 6.0.7 on 2026-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='reply_generation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='auto_reply_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(choices=[('openai/gpt-4o-mini', 'GPT-4o Mini'), ('openai/gpt-4o', 'GPT-4o'), ('anthropic/claude-3.5-sonnet', 'Claude 3.5 Sonnet'), ('google/gemini-2.0-flash-001', 'Gemini 2.0 Flash'), ('groq/llama-3.1-8b-instant', 'Llama 3.1 8B (Groq Free)'), ('groq/llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)'), ('groq/mixtral-8x7b-32768', 'Mixtral 8x7B (Groq)')], default='groq/llama-3.1-8b-instant', max_length=100),
        ),
    ]
