# Generated by Django 6.0.7 on 2026-08-04 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
        ('ai_service', '0002_aiconfig_reply_generation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='auto_assign_on_escalation',
            field=models.BooleanField(default=True, help_text='Auto-assign to agent on escalation'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='auto_assign_routing',
            field=models.CharField(choices=[('least_busy', 'Least Busy'), ('round_robin', 'Round Robin')], default='least_busy', help_text='Routing strategy for auto-assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='auto_assign_team_id',
            field=models.UUIDField(blank=True, help_text='Team to assign escalated conversations (null = org-wide)', null=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='escalation_increase_priority',
            field=models.BooleanField(default=True, help_text="Increase priority to 'high' on escalation"),
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('urgent_hours', models.FloatField(default=1, help_text='SLA deadline for urgent priority (hours)')),
                ('high_hours', models.FloatField(default=4, help_text='SLA deadline for high priority (hours)')),
                ('normal_hours', models.FloatField(default=8, help_text='SLA deadline for normal priority (hours)')),
                ('low_hours', models.FloatField(default=24, help_text='SLA deadline for low priority (hours)')),
                ('warn_before_minutes', models.IntegerField(default=15, help_text='Warn before SLA breach (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_config', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
            },
        ),
    ]
